name: podcasts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.6
  - pip=21.0.1
  - numpy=1.19.5
  - pandas=1.2.3
  - omegaconf=2.0.6 
  - sox=14.4.2
  - pytables=3.6.1
  - matplotlib=3.3.4
  - jupyterlab=3.0.12
  - sentencepiece=0.1.95
  - transformers=4.4.2
  - elasticsearch-dsl=7.3.0
  - pip:
    - tensorflow==2.4.1
    - tf-slim==1.1.0 
    - torch==1.8.1
    - opensmile==2.0.0
    - librosa==0.8.0